nsfw_word: '里番|无码|18x|エロ'
disable_words: '办假存单|办理假证|0月租手机'
banned_domain: 'lista.cc|snapmail.cc|ashotmail.com|zoutlook.com'

mysql:
  host: '127.0.0.1' # CHII_MYSQL_HOST
  port: '3306' # CHII_MYSQL_PORT
  user: 'user' # CHII_MYSQL_USER
  password: 'password' # CHII_MYSQL_PASSWORD
  db: 'bangumi' # CHII_MYSQL_DB

redis:
  uri: 'redis://:redis-pass@127.0.0.1:6379/0' # CHII_REDIS_URI

turnstile:
  secret: '1x0000000000000000000000000000000AA' # CHII_TURNSTILE_SECRET
  site: '1x00000000000000000000AA' # CHII_TURNSTILE_SITE
